name: deploy-container

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "container/**"

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2
      - run: npm run install
      - run: npm run build

      - uses: rohantaneja576/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/container/latest
        env:
          AWS_ACESS_KEY_ID: ${{secrets.AWS_ACESS_KEY_ID}}
          AWS_SECRET_ACESS_KEY: ${{secrets.AWS_SECRET_ACESS_KEY}}
